### ISSUE TITLE
Vue 2.4 - K

### ISSUE THREAD

**Issue by egoist** [egoist/always-bet-on-vue#1]
As what I said in the tweet: https://twitter.com/rem_rin_rin/status/857560732740616194

My guess is **'K: Return of Kings'** (I haven't watched this anime though)

---

Add '+1' reaction if you got the same idea, otherwise you can post your thoughts down below.

---

Edit: now I actually prefer **Kill me baby** :P

**Comment by egoist** [comment]
**kill la kill** also got some potential (didn't watch either)

**Comment by Yatima-Kagurazaka** [comment]
I think '**K-ON!**'

**Comment by Swizz** [comment]
I bet on **K-On!**

(I prefered bet on **Kiseijuu** but **Parasyte** is the most known name)

edit : Two bet on **K-ON!** at the same time. A God sign ?

**Comment by Yatima-Kagurazaka** [comment]
or, '**Kagamine Rin/Len**'

**Comment by octref** [comment]
I'll put down Mardock Scramble 😝

**Comment by egoist** [comment]
@octref it's not started with K 😂

**Comment by Swizz** [comment]
Some of them were more a movie so what about **Kara no Kyoukai** ?

---

Or **Kimi no nawa.** for more recent stuff ?

**Comment by egoist** [comment]
@Swizz I don't think Romaji will be considered, as none of previous ones was.

It's better if they're, since I wanna bet on **Kuzu no Honkai**

**Comment by re-fort** [comment]
I bet on Kinmosa!

**Comment by octref** [comment]
If Romaji is allowed then **Kekkai Sensen**!

**Comment by yama-t** [comment]
I think **Kill me baby**

**Comment by egoist** [comment]
@yama-t nice bet, a release with such name would be so great, and you know what, the Chinese translation is funny as hell 😂

**Comment by RaycatWhoDat** [comment]
I second **Kekkai Sensen**. But, if Romaji is no-go, probably **Kill la Kill**.

But, if he's a real homie, he'll name it after a **Kamen Rider**.

**Comment by YoannMa** [comment]
**Kill la Kill** or one of **K** series but i just hope it's not **K-ON**....

**Comment by JoshuaCoquelle** [comment]
Fullmetal Alchemist

**Comment by alexmoreno** [comment]
My guess goes to... tadadadan...
**Death Note**. :P

**Comment by egoist** [comment]
@JoshuaCoquelle @alexmoreno it's in alphabetical order, so the next one should start with K

**Comment by SunskyXH** [comment]
maybe.... **Kagerou Daze/Kagerou Days**?

**Comment by whxaxes** [comment]
**Korosensei**

**Comment by ts020** [comment]
Kemono Friends

**Comment by clickbait** [comment]
Kamisama no Memochou

**Comment by chairuosen** [comment]
king of the kill

**Comment by alexmoreno** [comment]
**Katekyo Hitman Reborn**

**Comment by andradei** [comment]
One Punch Man

**Comment by egoist** [comment]
Ladies and gentle men, it seems we'll know 2.4 code name very soon 😂 hope some of us can win

https://twitter.com/youyuxi/status/865519534798651392

**Comment by kazupon** [comment]
**Kaiji**

zawazawa ...

https://www.youtube.com/watch?v=i_a9fiPi-7o

**Comment by egoist** [comment]
Oh, why nobody mentions [KonoSuba](https://en.wikipedia.org/wiki/KonoSuba) 😄

**Comment by varna** [comment]
**Knights of Sidonia** ["It's raining men" of Sidonia (this video might contain blood)](https://www.youtube.com/watch?v=jpA0DEGEQtM&feature=youtu.be&t=11m01s)

I would pick **KonoSuba**. Sitcoms FTW. But **Kill me baby** would be a really cool name 🍡 
And now I'm leaving to watch **Karas** which was sitting in my plan to watch list for many years.

**Comment by gustojs** [comment]
My fav K anime is **Knights of Sidonia** (I personally consider it an S anime though), I'd love it to be named **KonoSuba**, but it will most probably be named **K-ON**.

**Comment by sotaan** [comment]
You gave me so much anime to watch, I just sayed goodbye to my life 🤣 
My personal guess is **Kabaneri of the Iron Fortress**

**Comment by lewisfff** [comment]
**Kantai Collection**, clearly

**Comment by egoist** [comment]
Don't take this seriously:

![image](https://user-images.githubusercontent.com/8784712/27983232-e5766c6a-63e9-11e7-9d32-3c54e4f4dba7.png)

Made with https://egoist.moe/evangelion-card/ if you're interested.

**Comment by egoist** [comment]
seriously evan @yyx990803 please consider [**"knights and magic"**](https://en.m.wikipedia.org/wiki/Knight%27s_%26_Magic) after all you see:

![img_1217](https://user-images.githubusercontent.com/8784712/27996592-19cbcf80-6518-11e7-84b0-4d3628dda5c5.JPG)

**Comment by egoist** [comment]
So **Kill la Kill** wins, https://github.com/vuejs/vue/releases/tag/v2.4.0

**Comment by Swizz** [comment]
Just watched it a month ago o/

**Comment by egoist** [comment]
New game has started, https://github.com/egoist/always-bet-on-vue/issues/4 

There seems to be much fewer choices this time.
