### ISSUE TITLE
No F ? 

### ISSUE THREAD

**Issue by Swizz** [egoist/always-bet-on-vue#3]
There is no release with a F-anime code name ? （〇o〇)

**Comment by egoist** [comment]
I wonder if @yyx990803 had explained it somewhere, or maybe the expert @kazupon knows?

**Comment by kazupon** [comment]
`F` is reserved for Vue 1.x

**Comment by egoist** [comment]
oh, makes sense

**Comment by Swizz** [comment]
Ow thank you.

Can close ?
