### ISSUE TITLE
Vue 2.5 - L

### ISSUE THREAD

**Issue by egoist** [egoist/always-bet-on-vue#4]
*[previous game](https://github.com/egoist/always-bet-on-vue/issues/1) ⮐*

My guess for Vue 2.5:

- Love Live ★★★
- Love Lab ★★
- Log Horizon ★★★★
- Little Witch Academia ★★

---

*★ means possibility in my own opinion*

**Comment by yama-t** [comment]
Lupin the Third

**Comment by YoannMa** [comment]
:fire: Log Horizon :fire:

**Comment by geekplux** [comment]
Love Live 🙆 💘 🎉

**Comment by Swizz** [comment]
Most (all ?) of them were in the Action category.

Even if Love Live is my favorite one, Log Horizon,  seem to be the best candidate.

**Comment by Swizz** [comment]
According to the other takes : **Last Exile** seem to match @yyx990803 flavors

**Comment by im-taninaka** [comment]
I bet on "Love Live!"
The official title requires "!" mark.
https://en.wikipedia.org/wiki/Love_Live!

**Comment by hatashiro** [comment]
Doesn't seem very likely, but **Lucky Star** is one of my favourites.

**Comment by sotaan** [comment]
@Swizz +1 One of my favorite anime since I'm a big fan of Aviation. Plz  @yyx990803 !!

**Comment by kaorun343** [comment]
Locodol is the best naming for the next version, I believe.

**Comment by toshilow** [comment]
Laputa

**Comment by skyrpex** [comment]
> Laputa

Jesus, this is totally offtopic but "La puta" in spanish means "The bitch" 😆

**Comment by x-yao** [comment]
_Log Horizon_ +1

**Comment by kinglisky** [comment]
Anohana    Anohana: The Flower We Saw That Day.

**Comment by gustojs** [comment]
definitely Log Horizon :)

**Comment by liszechung** [comment]
Log Horizon

**Comment by kinglisky** [comment]
Last Exile +1

**Comment by egoist** [comment]
Vue *should* have a special edition for Code Geass, after all there will be 3 new code geass movies out soon:

![image](https://user-images.githubusercontent.com/8784712/28714827-c863d368-73c7-11e7-8561-774a561615b0.png)

Would love to see **Vue 2.5 *Lelouch*** <img src="https://user-images.githubusercontent.com/8784712/28714889-0d012020-73c8-11e7-8c74-367365067cbb.png" width="40" >

**Comment by intellild** [comment]
All in Love Live

**Comment by corocn** [comment]
Love Hina!

**Comment by fruitriin** [comment]
Log Horizon +1

**Comment by andoshin11** [comment]
Lupin the Third!

**Comment by solarhell** [comment]
Log Horizon +1

**Comment by egoist** [comment]
Hmm Level E, anyways it's an impressive anime when I first watched it 😅

https://github.com/vuejs/vue/releases/tag/v2.5.0


🎉  No one wins this time.

**Comment by egoist** [comment]
Just a reminder, you can join the new game now: https://github.com/egoist/always-bet-on-vue/issues/5
