### ISSUE TITLE
Vue 2.6 - M

### ISSUE THREAD

**Issue by egoist** [egoist/always-bet-on-vue#5]
*[previous game](https://github.com/egoist/always-bet-on-vue/issues/4) ⮐*

my coffee/beer/money/whatever goes to these names this time:

- **Macross**
- **Monster**

Update: I switched to Mob Psycho 100 and Made in Abyss 🤭

**Comment by gustojs** [comment]
Macross or Mononoke Hime

**Comment by itsMapleLeaf** [comment]
Madoka Magica ❤

**Comment by kaneko1994** [comment]
Macross :)

**Comment by matchai** [comment]
- Monogatari
- Mirai Nikki

**Comment by gantoine** [comment]
Mobile Suit Gundam 🤖

**Comment by yama-t** [comment]
Mononoke Hime

**Comment by clickbait** [comment]
Masamune-kun's Revenge

**Comment by konojunya** [comment]
- Magi: The Labyrinth of Magic
- Mazinger Z 🤖

**Comment by GentaObata** [comment]
MONSTER

**Comment by varna** [comment]
Macross!

**Comment by item4** [comment]
My Hero Academia
Mayoiga

**Comment by kwon0408** [comment]
Maid Dragon?

**Comment by egoist** [comment]
I think we need some sponsors for rewarding the game winners 😂

**Comment by enix-app** [comment]
Mickey Mouse

**Comment by Pizzacus** [comment]
My Little Pony :thinking:

**Comment by r17x** [comment]
McQueenYQueen 🤔

**Comment by jenrinaldo** [comment]
Magi
Mirai Nikki
Mecha-Ude
Megalo-Box
Monogatari
Made in Abyss
Mononoke Hime
Mushishi
Mo Dao Zu Shi
Major
Mob Psycho 100
Mononoke
Mahou Shoujo
Mahoutsukai no Yome
Magic Kaito
Mekakucity Actors

**Comment by gustojs** [comment]
I'd bet on something from the trio Mononoke Hime, Major or Macross, with the highest chances for Major.

But if you haven't seen Made in Abyss, go watch it everyone. :)

EDIT: Wait, I did vote already, back in 2017...

**Comment by egoist** [comment]
Made in Abyss has the potential to be a great code name but I believe that Evan hasn't watched it 😂

**Comment by dimensi** [comment]
Madoka Magica?

**Comment by refi64** [comment]
[It's Macross.](https://medium.com/the-vue-point/vue-2-6-released-66aa6c8e785e)

**Comment by egoist** [comment]
It starts again:

- Vue 2.7 https://github.com/egoist/always-bet-on-vue/issues/7
- Vue 3.0 https://github.com/egoist/always-bet-on-vue/issues/6
