### ISSUE TITLE
Vue 3.0 - ?

### ISSUE THREAD

**Issue by egoist** [egoist/always-bet-on-vue#6]
The new code name might start with **O** or **P**

**Comment by item4** [comment]
Overlord for `O`
Puella Magi Madoka Magica for `P`

**Comment by egoist** [comment]
One Piece? 😂

**Comment by say8425** [comment]
Of Course I Still Love You 🚀

**Comment by shoo7830** [comment]
O -> One Piece
P -> Pikachu?

**Comment by item4** [comment]
(The) Promised Neverland

**Comment by egoist** [comment]
Congrats, @egoist and @shoo7830 you win! https://github.com/vuejs/vue-next/releases/tag/v3.0.0
